USE [QLSINHVIEN]
GO
/****** Object:  Table [dbo].[BANGDIEM]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANGDIEM](
	[MASV] [nvarchar](20) NOT NULL,
	[MAHP] [varchar](20) NOT NULL,
	[DIEMTHI] [varbinary](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MASV] ASC,
	[MAHP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOCPHAN]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOCPHAN](
	[MAHP] [varchar](20) NOT NULL,
	[TENHP] [nvarchar](100) NOT NULL,
	[SOTC] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MAHP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOP]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOP](
	[MALOP] [varchar](20) NOT NULL,
	[TENLOP] [nvarchar](100) NOT NULL,
	[MANV] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[MALOP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [varchar](20) NOT NULL,
	[HOTEN] [nvarchar](100) NOT NULL,
	[EMAIL] [varchar](100) NULL,
	[LUONG] [varbinary](max) NULL,
	[TENDN] [nvarchar](100) NOT NULL,
	[MATKHAU] [nvarchar](max) NOT NULL,
	[PUBKEY] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SINHVIEN]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SINHVIEN](
	[MASV] [nvarchar](20) NOT NULL,
	[HOTEN] [nvarchar](100) NOT NULL,
	[NGAYSINH] [datetime] NULL,
	[DIACHI] [nvarchar](200) NULL,
	[MALOP] [varchar](20) NULL,
	[TENDN] [nvarchar](100) NOT NULL,
	[MATKHAU] [varchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MASV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[BANGDIEM]  WITH CHECK ADD FOREIGN KEY([MAHP])
REFERENCES [dbo].[HOCPHAN] ([MAHP])
GO
ALTER TABLE [dbo].[BANGDIEM]  WITH CHECK ADD FOREIGN KEY([MASV])
REFERENCES [dbo].[SINHVIEN] ([MASV])
GO
ALTER TABLE [dbo].[LOP]  WITH CHECK ADD FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
/****** Object:  StoredProcedure [dbo].[SP_DEL_LOP]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_DEL_LOP] 
    @MALOP VARCHAR(20)
AS
BEGIN
    DELETE FROM LOP
    WHERE MALOP = @MALOP
END
GO
/****** Object:  StoredProcedure [dbo].[SP_DEL_NHANVIEN]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_DEL_NHANVIEN]
(
    @MANV VARCHAR(20)
)
AS
BEGIN
    DELETE FROM NHANVIEN
    WHERE MANV = @MANV;
END;
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_DIEM]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_INS_DIEM]
(
	@TK VARCHAR(20),
	@MASV NVARCHAR(20),
	@MAHP VARCHAR(20),
	@DIEMTHI VARBINARY(max)
)
AS
BEGIN
	DECLARE @Manv VARCHAR(20);
	SELECT @Manv = MANV 
	FROM NHANVIEN 
	WHERE TENDN = @TK;

	INSERT INTO BANGDIEM (MASV, MAHP, DIEMTHI)
	VALUES (@MASV, @MAHP, @DIEMTHI);
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_LOP]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_INS_LOP] 
    @MALOP VARCHAR(20),
    @TENLOP NVARCHAR(100),
    @MANV VARCHAR(20)
AS
BEGIN
    INSERT INTO LOP (MALOP, TENLOP, MANV)
    VALUES (@MALOP, @TENLOP, @MANV)
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_NHANVIEN]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[SP_INS_NHANVIEN]
(
	@MANV varchar(20),
	@HOTEN nvarchar(100),
	@EMAIL varchar(20),
	@LUONG VARBINARY(max),
	@TENDN nvarchar(100),
	@MATKHAU nvarchar(MAX),
	@PUBKEY VARCHAR(20)

)
As
	Begin
		INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
		VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MATKHAU, @PUBKEY);
	END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_SINHVIEN]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_INS_SINHVIEN]
(
	@MASV NVARCHAR(20),
	@HOTEN NVARCHAR(100),
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20),
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(MAX)
)
As
	BEGIN
		
		INSERT INTO SINHVIEN
		VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MATKHAU)
	END
GO
/****** Object:  StoredProcedure [dbo].[SP_LOG_IN]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[SP_LOG_IN]
(
	@TENDN nvarchar(100),
	@MATKHAU nvarchar(MAX)
)
As
	Begin
		
		DECLARE @COUNT INT;
		SET @COUNT = (SELECT COUNT(*) FROM NHANVIEN WHERE TENDN = @TENDN and MATKHAU = @MATKHAU)
		if @COUNT = 1
			BEGIN SELECT COUNT(*) FROM NHANVIEN WHERE TENDN = @TENDN and MATKHAU = @MATKHAU RETURN END
		ELSE
			BEGIN SELECT COUNT(*) FROM SINHVIEN WHERE TENDN = @TENDN and MATKHAU = @MATKHAU END
	END
GO
/****** Object:  StoredProcedure [dbo].[SP_SEL_BANGDIEM]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[SP_SEL_BANGDIEM]
(
	@TK VARCHAR(20)
)
AS
	BEGIN
		DECLARE @Manv VARCHAR(20);
		SELECT @Manv = MANV 
		FROM NHANVIEN 
		WHERE TENDN = @TK;
		SELECT bd.MASV,MAHP,DIEMTHI
		FROM BANGDIEM bd
		JOIN SINHVIEN sv ON bd.MASV = sv.MASV
		JOIN LOP l ON sv.MALOP = l.MALOP
		WHERE l.MANV = @MANV;
	END
GO
/****** Object:  StoredProcedure [dbo].[SP_SEL_SINHVIEN]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_SEL_SINHVIEN]
    @TENDN VARCHAR(20)
AS
BEGIN
    DECLARE @Manv VARCHAR(20);

    -- Retrieve MANV based on TENDN and assign it to @Manv
    SELECT @Manv = MANV 
    FROM NHANVIEN 
    WHERE TENDN = @TENDN;

    -- Retrieve student details based on the MANV of the staff member
    SELECT 
        SINHVIEN.MASV,
        SINHVIEN.HOTEN,
        SINHVIEN.NGAYSINH,
        SINHVIEN.DIACHI,
        SINHVIEN.MALOP,
        SINHVIEN.TENDN,
        SINHVIEN.MATKHAU
    FROM 
        SINHVIEN
    JOIN 
        LOP ON SINHVIEN.MALOP = LOP.MALOP
    JOIN 
        NHANVIEN ON LOP.MANV = NHANVIEN.MANV
    WHERE 
        LOP.MANV = @Manv;
END
GO
/****** Object:  StoredProcedure [dbo].[SP_UPD_LOP]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_UPD_LOP] 
    @MALOP VARCHAR(20),
    @TENLOP NVARCHAR(100),
    @MANV VARCHAR(20)
AS
BEGIN
    UPDATE LOP
    SET TENLOP = @TENLOP,
        MANV = @MANV
    WHERE MALOP = @MALOP
END

GO
/****** Object:  StoredProcedure [dbo].[SP_UPD_NHANVIEN]    Script Date: 29/5/2024 2:52:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_UPD_NHANVIEN]
(
    @MANV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(100),
    @LUONG VARBINARY(MAX)
)
AS
BEGIN
    IF @LUONG=''
    BEGIN
		UPDATE NHANVIEN
        SET HOTEN = @HOTEN,
            EMAIL = @EMAIL
        WHERE MANV = @MANV;
        
    END
    ELSE
    BEGIN
        UPDATE NHANVIEN
        SET HOTEN = @HOTEN,
            EMAIL = @EMAIL,
            LUONG = @LUONG
        WHERE MANV = @MANV;
    END
END;
GO
